name: Sync Unlock-Music to Aliyun

on:  
  workflow_dispatch:

jobs:  
  build:    
    runs-on: ubuntu-latest    
    steps:      
      - name: 登录阿里云镜像仓库        
        run: docker login -u ${{ secrets.ALIYUN_USERNAME }} -p ${{ secrets.ALIYUN_PASSWORD }} crpi-jlzkfoisf4mhudx0.cn-heyuan.personal.cr.aliyuncs.com      
        
      - name: 从 Docker Hub 拉取 Unlock-Music 镜像        
        run: docker pull yuanter/unlock-music:latest      
        
      - name: 打上你的阿里云专属标签        
        run: docker tag yuanter/unlock-music:latest crpi-jlzkfoisf4mhudx0.cn-heyuan.personal.cr.aliyuncs.com/fnnas-docker/unlock-music:latest      
        
      - name: 推送镜像到你的阿里云仓库        
        run: docker push crpi-jlzkfoisf4mhudx0.cn-heyuan.personal.cr.aliyuncs.com/fnnas-docker/unlock-music:latest
