name: Auto Sync Docker Images to Aliyun

on:
  workflow_dispatch:      # 保留手动触发按钮
  schedule:
    - cron: '0 2 * * 3'   # 定时任务：每周三凌晨2点(UTC)自动运行，保持所有镜像最新

# 提取公共环境变量，让代码更简洁
env:
  ALIYUN_REGISTRY: crpi-jlzkfoisf4mhudx0.cn-heyuan.personal.cr.aliyuncs.com
  ALIYUN_NAMESPACE: fnnas-docker

jobs:
  sync-images:
    runs-on: ubuntu-latest
    strategy:
      # 限制最大并发数为 1，强制任务一个接一个地按顺序串行执行
      max-parallel: 1      
      # 开启 fail-fast，如果当前镜像同步失败，立即停止后续尚未执行的任务
      fail-fast: true      
      matrix:
        # 【镜像清单】以后加镜像，只需要在这个列表里增加两行即可！
        image:
          # 1. 音乐解锁
          - source: 'yuanter/unlock-music:latest'
            target: 'unlock-music:latest'
            
          # 2. OpenClaw
          - source: 'ghcr.io/phioranex/openclaw-docker:latest'
            target: 'openclaw:latest'

          # 3. Ollama 大模型引擎
          - source: 'ollama/ollama:latest'
            target: 'ollama:latest'

          # 4. Open WebUI 绝美聊天网页端 
          - source: 'ghcr.io/open-webui/open-webui:main'
            target: 'open-webui:main'

          # 5. nginx
          - source: 'nginx:latest'
            target: 'nginx:latest'
            
          # 6. MetaTube 影视刮削服务端
          - source: 'ghcr.io/metatube-community/metatube-server:latest'
            target: 'metatube-server:latest'
            
          # 7. filebrowser
          - source: 'filebrowser/filebrowser:latest'
            target: 'filebrowser:latest'

          # 8. 推特视频下载
          - source: 'alexta69/metube:latest'
            target: 'metube:latest'

          # 9. nginx-basic-auth
          - source: 'dtcokr/nginx-basic-auth:latest'
            target: 'nginx-basic-auth:latest'
            
          
          
    steps:      
      - name: 登录阿里云镜像仓库        
        run: docker login -u ${{ secrets.ALIYUN_USERNAME }} -p ${{ secrets.ALIYUN_PASSWORD }} ${{ env.ALIYUN_REGISTRY }}
        
      - name: 拉取源镜像 [ ${{ matrix.image.source }} ]
        run: docker pull ${{ matrix.image.source }}      
        
      - name: 修改为阿里云专属标签        
        run: docker tag ${{ matrix.image.source }} ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAMESPACE }}/${{ matrix.image.target }}      
        
      - name: 推送镜像到阿里云仓库        
        run: docker push ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAMESPACE }}/${{ matrix.image.target }}

        
  # ----------------------------------------
  # 任务 2：源码构建 ReClip 并推送 
  # ----------------------------------------
  build-reclip:
     runs-on: ubuntu-latest
     steps:
      - name: 检出 ReClip 官方源码
        uses: actions/checkout@v4
        with:
          repository: 'averygan/reclip' # 直接拉取原作者的仓库
          ref: 'main'                   # 始终拉取最新的主分支代码
          
      - name: 登录阿里云镜像仓库
        run: docker login -u ${{ secrets.ALIYUN_USERNAME }} -p ${{ secrets.ALIYUN_PASSWORD }} ${{ env.ALIYUN_REGISTRY }}
        
      - name: 在 GitHub 服务器上本地构建 Docker 镜像
        run: docker build -t ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAMESPACE }}/reclip:latest .
        
      - name: 将构建好的镜像推送到阿里云
        run: docker push ${{ env.ALIYUN_REGISTRY }}/${{ env.ALIYUN_NAMESPACE }}/reclip:latest
